import { NextRequest, NextResponse } from 'next/server';
import JSZip from 'jszip';
import { z } from 'zod';

const exportSchema = z.object({
  projectDefinition: z.any(),
  prd: z.string(),
  features: z.any(),
  architecture: z.any(),
  tasks: z.array(z.any()),
  agentInstructions: z.string()
});

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const validated = exportSchema.parse(body);

    const zip = new JSZip();

    // Root files
    zip.file('README.md', generateReadme(validated.projectDefinition));
    zip.file('AGENTS.md', validated.agentInstructions);

    // Docs folder
    const docs = zip.folder('docs')!;
    docs.file('PRD.md', validated.prd);
    docs.file('architecture.md', generateArchitectureMarkdown(validated.architecture, validated.projectDefinition));

    // Features folder
    const featuresFolder = docs.folder('features')!;
    for (const feature of validated.features) {
      featuresFolder.file(`${feature.id?.toLowerCase() || 'feature'}.md`, generateFeatureMarkdown(feature));
    }

    // Tasks folder
    const tasksFolder = zip.folder('tasks')!;
    tasksFolder.file('README.md', '# Implementation Tasks\n\nFollow the order below for implementation.\n\n## Strategy\n' + 
      (validated.projectDefinition.implementationStrategy || 'frontend-first') + '\n\n');
    
    for (const task of validated.tasks) {
      tasksFolder.file(`${task.id}.md`, generateTaskMarkdown(task, validated.projectDefinition));
    }

    // Generate ZIP buffer
    const buffer = await zip.generateAsync({ type: 'nodebuffer' });

    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${validated.projectDefinition.name?.toLowerCase().replace(/\s+/g, '-') || 'project'}-spec.zip"`
      }
    });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json({ error: error.issues }, { status: 400 });
    }
    console.error('Export error:', error);
    return NextResponse.json({ error: 'Failed to generate export package' }, { status: 500 });
  }
}

function generateReadme(project: any): string {
  return `# ${project.name || 'Project'}

## Project Overview
${project.summary || 'No summary available.'}

## Platform
${project.platform?.join(', ') || 'Web'}

## Users
${project.users?.join(', ') || 'Users'}

## Implementation Strategy
${project.implementationStrategy || 'frontend-first'}

---
Generated by AgentSpec
`;
}

function generateArchitectureMarkdown(architecture: any, project?: any): string {
  let data: any = architecture;
  if (
    data &&
    typeof data === 'object' &&
    !Array.isArray(data) &&
    typeof (data as Record<string, any>).architecture === 'object' &&
    (data as Record<string, any>).architecture !== null
  ) {
    data = (data as Record<string, any>).architecture;
  }
  const safeStringify = (value: unknown): string => {
    try {
      const result = JSON.stringify(value);
      return typeof result === 'string' ? result : String(value);
    } catch {
      return String(value);
    }
  };
  const formatValue = (value: unknown): string => {
    if (value === null || value === undefined) return 'N/A';
    if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') return String(value);
    return safeStringify(value);
  };
  const title = project?.name ? `${project.name} - Architecture` : 'Architecture';
  let md = `# ${title}\n`;
  if (data === null || data === undefined) {
    return md + '\nNo architecture details available.\n';
  }
  if (typeof data !== 'object') {
    return md + `\n${formatValue(data)}\n`;
  }
  if (Array.isArray(data)) {
    if (data.length === 0) return md + '\nNo architecture details available.\n';
    return md + '\n' + data.map((item) => `- ${formatValue(item)}`).join('\n') + '\n';
  }
  const entries = Object.entries(data as Record<string, unknown>);
  if (entries.length === 0) {
    return md + '\nNo architecture details available.\n';
  }
  for (const [key, value] of entries) {
    const heading = key
      .replace(/[_-]+/g, ' ')
      .replace(/([a-z])([A-Z])/g, '$1 $2')
      .replace(/^\w/, (c) => c.toUpperCase());
    md += `\n## ${heading}\n`;
    if (Array.isArray(value)) {
      if (value.length === 0) {
        md += 'None\n';
      } else {
        md += (value as unknown[]).map((item) => `- ${formatValue(item)}`).join('\n') + '\n';
      }
    } else if (value !== null && typeof value === 'object') {
      const objEntries = Object.entries(value as Record<string, unknown>);
      if (objEntries.length === 0) {
        md += 'None\n';
      } else {
        for (const [k, v] of objEntries) {
          md += `- **${k}**: ${formatValue(v)}\n`;
        }
      }
    } else if (value === null || value === undefined) {
      md += 'N/A\n';
    } else if (typeof value === 'string' && value.length > 0) {
      md += `${value}\n`;
    } else if (typeof value === 'number' || typeof value === 'boolean') {
      md += `${String(value)}\n`;
    } else {
      md += `${formatValue(value)}\n`;
    }
  }
  return md;
}

function generateFeatureMarkdown(feature: any): string {
  return `# ${feature.name || 'Feature'}

## ID
${feature.id || 'N/A'}

## Purpose
${feature.purpose || ''}

## Actors
${feature.actors?.map((a: string) => `- ${a}`).join('\n') || '- None specified'}

## Main Flow
${feature.mainFlow?.map((f: string) => `→ ${f}`).join('\n') || '- Not defined'}

## Requirements
${feature.requirements?.map((r: string) => `- ${r}`).join('\n') || '- None'}

## Business Rules
${feature.businessRules?.map((r: string) => `- ${r}`).join('\n') || '- None'}

## Edge Cases
${feature.edgeCases?.map((e: string) => `- ${e}`).join('\n') || '- None'}

## Acceptance Criteria
${feature.acceptanceCriteria?.map((a: string) => `- ${a}`).join('\n') || '- None'}
`;
}

function generateTaskMarkdown(task: any, project: any): string {
  return `# ${task.title || 'Task'}

## ID
${task.id || 'N/A'}

## Type
${task.type || 'frontend'}

## Feature
${task.featureId || 'N/A'}

## Dependencies
${task.dependencies?.map((d: string) => `- ${d}`).join('\n') || 'None'}

## References
${task.references?.map((r: string) => `- ${r}`).join('\n') || 'None'}

## Requirements
${task.requirements?.map((r: string) => `- ${r}`).join('\n') || '- None'}

## Acceptance Criteria
${task.acceptanceCriteria?.map((a: string) => `- ${a}`).join('\n') || '- None'}
`;
}
